use_frameworks!

target 'BlinkingLabel_Example' do
  pod 'BlinkingLabel', :path => '../'

  target 'BlinkingLabel_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
